export const textStyles = {
    headingXXl: {
        fontSize: 80,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 500,
        fontFamily: 'inter',
    },
    headingXL: {
        fontSize: 44,
        lineHeight: 1,
        letterSpacing: '-0.01em',
        fontWeight: 500,
        fontFamily: 'inter',
    },
    healingL: {
        fontSize: 56,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 450,
        fontFamily: 'inter',
    },
    headingM: {
        fontSize: 32,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 450,
        fontFamily: 'inter',
    },
    headingS: {
        fontFamily: 'inter',
        fontSize: 26,
        lineHeight: 1.2,
        fontWeight: 450,
    },
    bodyXL: {
        fontFamily: 'inter',
        fontSize: 22,
        lineHeight: 1.3,
        fontWeight: 400,
    },
    bodyL: {
        fontFamily: 'inter',
        fontSize: 18,
        lineHeight: 1.3,
        fontWeight: 400,
    },
    bodyM: {
        fontFamily: 'inter',
        fontSize: 16,
        lineHeight: 1.2,
        fontWeight: 500,
    },
    bodyS: {
        fontFamily: 'inter',
        fontSize: 14,
        lineHeight: 1.5,
        fontWeight: 500,
    },
    bodyXS: {
        fontFamily: 'inter',
        fontSize: 13,
        lineHeight: 1.5,
        fontWeight: 500,
    },
    bodyXXS: {
        fontFamily: 'inter',
        fontSize: 12,
        lineHeight: 1.5,
        fontWeight: 400,
    },
};
