export const textStyles = {
    heading: {
        fontSize: 80,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 500,
        fontFamily: 'inter',
    },
    subheading: {
        fontSize: 44,
        lineHeight: 1,
        letterSpacing: '-0.01em',
        fontWeight: 500,
        fontFamily: 'inter',
    },
    title: {
        fontSize: 56,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 450,
        fontFamily: 'inter',
    },
    subtitle: {
        fontSize: 36,
        lineHeight: 1,
        letterSpacing: '-0.02em',
        fontWeight: 450,
        fontFamily: 'inter',
    },
    extraExtraLarge: {
        fontFamily: 'inter',
        fontSize: 26,
        lineHeight: 1.2,
        fontWeight: 450,
    },
    extraLarge: {
        fontFamily: 'inter',
        fontSize: 22,
        lineHeight: 1.3,
        fontWeight: 400,
    },
    large: {
        fontFamily: 'inter',
        fontSize: 18,
        lineHeight: 1.3,
        fontWeight: 400,
    },
    medium: {
        fontFamily: 'inter',
        fontSize: 16,
        lineHeight: 1.2,
        fontWeight: 500,
    },
    small: {
        fontFamily: 'inter',
        fontSize: 14,
        lineHeight: 1.5,
        fontWeight: 500,
    },
    extraSmall: {
        fontFamily: 'inter',
        fontSize: 13,
        lineHeight: 1.5,
        fontWeight: 500,
    },
};
